FROM golang:1.23 AS builder
WORKDIR /app
COPY . .
RUN go mod download
ENV GOCACHE=/root/.cache/go-build
RUN --mount=type=cache,target="/root/.cache/go-build" go build -o app -ldflags="-X 'card/build.Date=$(date +"%a %d %b %Y")' -X 'card/build.Time=$(date +"%H:%M:%S %Z")'"

FROM ubuntu:22.04
RUN mkdir /app
WORKDIR /app
COPY --from=builder /app/app .
COPY --from=builder /app/web-content/ /web-content/
ENV HOST_DOMAIN=domain_name
ENTRYPOINT ["./app"]
